# Generated by Django 5.2.3 on 2025-07-19 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('constituency_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('assembly', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=120)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=100)),
                ('leader_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('voter', 'Voter'), ('candidate', 'Candidate'), ('chairperson', 'Chairperson')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VotingControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('duration_minutes', models.IntegerField(default=120)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_cnic', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('seat_type', models.CharField(choices=[('NA', 'NA'), ('PA', 'PA')], max_length=10)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.election')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.party')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('voter_cnic', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('na_constituency_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='na_constituency', to='main.constituency')),
                ('pa_constituency_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pa_constituency', to='main.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(choices=[('NA', 'NA'), ('PA', 'PA')], max_length=10)),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.candidate')),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voter')),
            ],
            options={
                'unique_together': {('voter', 'election', 'seat_type')},
            },
        ),
    ]
