# Generated by Django 5.2.5 on 2025-08-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_email_user_otp_user_otp_created_at_voter_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='email',
        ),
    ]
